on:
  workflow_dispatch:

jobs:
  veracode_security_scan:
    runs-on: ubuntu-latest
    name: Run Veracode Scan
    steps:
      - name: Veracode Action Step
        id: Veracode 
        uses: veracode/veracode-dast-essentials-action
        with:
          VERACODE_WEBHOOK: '${{ secrets.CRASHTEST_WEBHOOK }}'
          VERACODE_SECRET_ID: '${{ secrets.VERACODE_SECRET_ID }}'
          VERACODE_SECRET_ID_KEY: '${{ secrets.VERACODE_SECRET_ID_KEY }}'
          pull-report: 'true'
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v1 
        with:
          report_paths: 'report.xml'
          github_token: ${{ secrets.GH_TOKEN }}
