on:
  workflow_dispatch:

jobs:
  veracode_security_scan:
    runs-on: ubuntu-latest
    name: Run Veracode Scan
    steps:
    - name: Veracode DAST Essentials Action Step
      id: veracode
      uses: veracode/veracode-dast-essentials-action@v1.0.1
      with:
        VERACODE_WEBHOOK: '${{ secrets.CRASHTEST_WEBHOOK }}'
        VERACODE_SECRET_ID: '${{ secrets.VERACODE_SECRET_ID }}'
        VERACODE_REGION: 'us'
        pull-report: 'true'
