name: Veracode Upload and Scan Demo

on:
# You can have this on whatever trigger you'd like (i.e. push, pull_request, etc)
  workflow_dispatch:


jobs: 
  build: 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    # check out your repo
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          cd app/
          mvn -B clean package --file pom.xml
          ls target/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: verademo-artifact
          path: app/target/verademo.war
          if-no-files-found: error

  veracode-sast-scan:
      runs-on: ubuntu-latest
      needs: build
      steps: 
        - uses: actions/checkout@v2
        - uses: actions/download-artifact@v2.0.10
          with: 
            name: verademo-artifact
            path: analysis/

        - name: Veracode Upload And Scan
          uses: veracode/veracode-uploadandscan-action@0.2.4
          with:
            # appname
            appname: VeraGHA
            # createprofile
            createprofile: false # default is true
            # filepath
            filepath: analysis/verademo.war
            # version
            version:  ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-${{ github.ref_name }} # default is Scan from Github job: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
            # vid
            vid: ${{secrets.VERACODE_API_ID}}
            # vkey
            vkey: ${{secrets.VERACODE_API_KEY}}
            # true or false
            #createsandbox: false # optional
            # name of the sandbox
            #sandboxname: # optional
            # wait X minutes for the scan to complete
            #scantimeout: # optional
            # modules to exclude from module selection
            #exclude: # optional
            # modules to include in module selection
            #include: # optional
            # business criticality - policy selection
            #criticality: # optional
            # filename pattern
            #pattern: # optional
            # replacement
            #replacement: # optional
            # specify to scan in a sandbox
            #sandboxid: # optional
            # All top level modules
            #scanallnonfataltoplevelmodules: # optional
            # platform selected modules
            #selected: # optional
            # selected modules like from previous scan
            #selectedpreviously: # optional
            # teams
            #teams: # optional
            # teams
            #toplevel: # optional
            # automatically delete the current scan if there are any errors when uploading files or starting the scan
            deleteincompletescan: 2 # optional
            # specify version of the Java API Wrapper; default is latest
            #javawrapperversion: # optional
            # show detailed diagnostic information, which you can use for debugging, in the output.
            debug: 1 # optional
    
        
